--[[
    Everness. Never ending discovery in Everness mapgen.
    Copyright (C) 2023 SaKeL <juraj.vajda@gmail.com>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to juraj.vajda@gmail.com
--]]

minetest.register_alias('default:water_source', 'rp_default:water_source')
minetest.register_alias('default:dirt_with_rainforest_litter', 'rp_default:dirt_with_grass')
minetest.register_alias('default:dirt_with_snow', 'rp_default:dirt_with_grass')
minetest.register_alias('default:dirt_with_coniferous_litter', 'rp_default:dirt_with_grass')
minetest.register_alias('default:dirt_with_grass', 'rp_default:dirt_with_grass')
minetest.register_alias('default:stick', 'rp_default:stick')
minetest.register_alias('default:paper', 'rp_default:paper')
minetest.register_alias('default:book', 'rp_default:book')
minetest.register_alias('default:skeleton_key', 'rp_default:skeleton_key')
minetest.register_alias('default:flint', 'rp_default:flint')
minetest.register_alias('default:obsidian_shard', 'rp_default:obsidian_shard')
minetest.register_alias('default:clay_brick', 'rp_default:clay_brick')
minetest.register_alias('default:mese_crystal_fragment', 'rp_default:mese_crystal_fragment')
-- Ingots
minetest.register_alias('default:gold_ingot', 'rp_default:gold_ingot')
minetest.register_alias('default:bronze_ingot', 'rp_default:bronze_ingot')
minetest.register_alias('default:tin_ingot', 'rp_default:tin_ingot')
minetest.register_alias('default:copper_ingot', 'rp_default:copper_ingot')
minetest.register_alias('default:steel_ingot', 'rp_default:steel_ingot')
minetest.register_alias('default:coal_lump', 'rp_default:coal_lump')
-- Tools
minetest.register_alias('default:pick_stone', 'rp_default:pick_stone')
minetest.register_alias('default:pick_bronze', 'rp_default:pick_bronze')
minetest.register_alias('default:pick_steel', 'rp_default:pick_steel')
minetest.register_alias('default:shovel_stone', 'rp_default:shovel_stone')
minetest.register_alias('default:shovel_bronze', 'rp_default:shovel_bronze')
minetest.register_alias('default:shovel_steel', 'rp_default:shovel_steel')
minetest.register_alias('default:axe_stone', 'rp_default:axe_stone')
minetest.register_alias('default:axe_bronze', 'rp_default:axe_bronze')
minetest.register_alias('default:axe_steel', 'rp_default:axe_steel')
minetest.register_alias('default:sword_stone', 'rp_default:sword_stone')
minetest.register_alias('default:sword_bronze', 'rp_default:sword_bronze')
minetest.register_alias('default:sword_steel', 'rp_default:sword_steel')
-- Items / Nodes
minetest.register_alias('default:bookshelf', 'rp_default:bookshelf')
minetest.register_alias('default:sign_wall_wood', 'rp_default:sign_wall_wood')
minetest.register_alias('default:ladder_wood', 'rp_default:ladder_wood')
minetest.register_alias('default:ladder_steel', 'rp_default:ladder_steel')
minetest.register_alias('default:glass', 'rp_default:glass')
minetest.register_alias('default:obsidian_glass', 'rp_default:obsidian_glass')
-- Trees
minetest.register_alias('default:tree', 'rp_default:tree')
minetest.register_alias('default:jungletree', 'rp_default:jungletree')
minetest.register_alias('default:pine_tree', 'rp_default:pine_tree')
minetest.register_alias('default:cactus', 'rp_default:cactus')
minetest.register_alias('default:large_cactus_seedling', 'rp_default:large_cactus_seedling')
minetest.register_alias('default:papyrus', 'rp_default:papyrus')
minetest.register_alias('default:junglegrass', 'rp_default:junglegrass')
minetest.register_alias('default:blueberry_bush_sapling', 'rp_default:blueberry_bush_sapling')
minetest.register_alias('default:sapling', 'rp_default:sapling')
minetest.register_alias('default:junglesapling', 'rp_default:junglesapling')
minetest.register_alias('default:pine_sapling', 'rp_default:pine_sapling')
minetest.register_alias('default:acacia_sapling', 'rp_default:acacia_sapling')
minetest.register_alias('default:aspen_sapling', 'rp_default:aspen_sapling')

minetest.register_alias('default:clay_lump', 'rp_default:clay_lump')
minetest.register_alias('default:tin_lump', 'rp_default:tin_lump')
minetest.register_alias('default:copper_lump', 'rp_default:copper_lump')
minetest.register_alias('default:iron_lump', 'rp_default:iron_lump')
minetest.register_alias('default:coalblock', 'rp_default:block_coal')
minetest.register_alias('default:steelblock', 'rp_default:steelblock')
minetest.register_alias('default:copperblock', 'rp_default:copperblock')
minetest.register_alias('default:tinblock', 'rp_default:tinblock')
minetest.register_alias('default:bronzeblock', 'rp_default:bronzeblock')
minetest.register_alias('default:mese', 'rp_default:mese')
minetest.register_alias('default:meselamp', 'rp_default:meselamp')
minetest.register_alias('default:obsidian', 'rp_default:obsidian')
minetest.register_alias('default:mese_crystal', 'rp_default:mese_crystal')
minetest.register_alias('default:diamond', 'rp_default:diamond')
minetest.register_alias('default:pick_mese', 'rp_default:pick_mese')
minetest.register_alias('default:shovel_mese', 'rp_default:shovel_mese')
minetest.register_alias('default:axe_mese', 'rp_default:axe_mese')
minetest.register_alias('default:sword_mese', 'rp_default:sword_mese')

minetest.register_alias('default:snowblock', 'rp_default:snowblock')
minetest.register_alias('default:ice', 'rp_default:ice')
minetest.register_alias('default:torch', 'rp_default:torch')
minetest.register_alias('default:cobble', 'rp_default:cobble')
minetest.register_alias('default:chest', 'rp_default:chest')
minetest.register_alias('default:snow', 'rp_default:snow')
minetest.register_alias('default:stone', 'rp_default:stone')
minetest.register_alias('default:sand', 'rp_default:sand')
minetest.register_alias('default:gravel', 'rp_default:gravel')
minetest.register_alias('default:stone_with_coal', 'rp_default:stone_with_coal')
minetest.register_alias('default:stone_with_iron', 'rp_default:stone_with_iron')
minetest.register_alias('default:stone_with_tin', 'rp_default:stone_with_tin')
minetest.register_alias('default:stone_with_gold', 'rp_default:stone_with_gold')
minetest.register_alias('default:stone_with_mese', 'rp_default:stone_with_mese')
minetest.register_alias('default:stone_with_diamond', 'rp_default:stone_with_diamond')
minetest.register_alias('default:lava_source', 'rp_default:water_source')
minetest.register_alias('default:mossycobble', 'rp_default:mossycobble')
minetest.register_alias('default:clay', 'rp_default:clay')
minetest.register_alias('default:dry_dirt_with_dry_grass', 'rp_default:dry_dirt_with_dry_grass')
minetest.register_alias('default:dry_dirt', 'rp_default:dry_dirt')
minetest.register_alias('default:coral_skeleton', 'everness:coral_skeleton')
minetest.register_alias('default:lava_flowing', 'rp_default:water_flowing')
minetest.register_alias('everness:cursed_brick_with_growth_wall', 'air')
minetest.register_alias('stairs:slab_cursed_brick_with_growth', 'air')
minetest.register_alias('default:fence_wood', 'rp_default:fence')
minetest.register_alias('default:torch_wall', 'rp_default:torch_wall')
minetest.register_alias('default:wood', 'rp_default:planks')
minetest.register_alias('default:junglewood', 'rp_default:junglewood')
minetest.register_alias('default:pine_wood', 'rp_default:pine_wood')
minetest.register_alias('default:mese_post_light_pine_wood', 'rp_default:mese_post_light_pine_wood')
minetest.register_alias_force('default:acacia_tree', 'rp_default:acacia_tree')
minetest.register_alias('default:dry_grass_4', 'rp_default:dry_grass_4')
minetest.register_alias('default:dry_grass_2', 'rp_default:dry_grass_2')
minetest.register_alias('default:dry_shrub', 'rp_default:dry_shrub')
minetest.register_alias('default:stonebrick', 'rp_default:stonebrick')
minetest.register_alias('default:jungleleaves', 'rp_default:jungleleaves')
minetest.register_alias('default:torch_ceiling', 'rp_default:torch_ceiling')
minetest.register_alias('default:goldblock', 'rp_default:goldblock')
minetest.register_alias('stairs:stair_coral_white_sandstone', 'mcl_stairs:stair_coral_white_sandstone')
minetest.register_alias('stairs:slab_coral_white_sandstone', 'mcl_stairs:slab_coral_white_sandstone')
minetest.register_alias('stairs:stair_coral_deep_ocean_sandstone_block', 'mcl_stairs:stair_coral_deep_ocean_sandstone_block')
minetest.register_alias('stairs:slab_coral_deep_ocean_sandstone_block', 'mcl_stairs:slab_coral_deep_ocean_sandstone_block')
minetest.register_alias('stairs:slab_coral_deep_ocean_sandstone_brick', 'mcl_stairs:slab_coral_deep_ocean_sandstone_brick')
minetest.register_alias('stairs:slab_coral_sandstone_brick', 'mcl_stairs:slab_coral_sandstone_brick')
minetest.register_alias('stairs:stair_coral_deep_ocean_sandstone_brick', 'mcl_stairs:stair_coral_deep_ocean_sandstone_brick')
minetest.register_alias('stairs:stair_crystal_forest_deep_ocean_sandstone_block', 'mcl_stairs:stair_crystal_forest_deep_ocean_sandstone_block')
minetest.register_alias('stairs:stair_crystal_forest_deep_ocean_sandstone_brick', 'mcl_stairs:stair_crystal_forest_deep_ocean_sandstone_brick')
minetest.register_alias('stairs:slab_crystal_forest_deep_ocean_sandstone_block', 'mcl_stairs:slab_crystal_forest_deep_ocean_sandstone_block')
minetest.register_alias('stairs:slab_crystal_forest_deep_ocean_sandstone_brick', 'mcl_stairs:slab_crystal_forest_deep_ocean_sandstone_brick')
minetest.register_alias('stairs:stair_forsaken_desert_brick_red', 'mcl_stairs:stair_forsaken_desert_brick_red')
minetest.register_alias('stairs:stair_forsaken_desert_chiseled_stone', 'mcl_stairs:stair_forsaken_desert_chiseled_stone')
minetest.register_alias('stairs:slab_forsaken_desert_chiseled_stone', 'mcl_stairs:slab_forsaken_desert_chiseled_stone')
minetest.register_alias('stairs:stair_junglewood', 'mcl_stairs:stair_junglewood')
minetest.register_alias('stairs:slab_junglewood', 'mcl_stairs:slab_junglewood')
minetest.register_alias('stairs:slab_dry_wood', 'mcl_stairs:slab_dry_wood')
minetest.register_alias('stairs:stair_dry_wood', 'mcl_stairs:stair_dry_wood')
minetest.register_alias('stairs:stair_wood', 'mcl_stairs:stair_wood')
minetest.register_alias('stairs:slab_stonebrick', 'mcl_stairs:slab_stonebrick')
minetest.register_alias('stairs:stair_inner_wood', 'mcl_stairs:stair_wood_inner')
minetest.register_alias('stairs:stair_outer_stonebrick', 'mcl_stairs:stair_stonebrick_outer')
minetest.register_alias('stairs:stair_stonebrick', 'mcl_stairs:stair_stonebrick')
-- minetest.register_alias('stairs:stair_cobble', 'mcl_stairs:stair_cobble')
minetest.register_alias('stairs:stair_mossycobble', 'mcl_stairs:stair_mossycobble')
minetest.register_alias('stairs:stair_outer_quartz_chiseled', 'mcl_stairs:stair_quartz_chiseled_outer')
minetest.register_alias('stairs:stair_quartz_chiseled', 'mcl_stairs:stair_quartz_chiseled')
minetest.register_alias('stairs:stair_inner_quartz_chiseled', 'mcl_stairs:stair_quartz_chiseled_inner')
minetest.register_alias('stairs:slab_quartz_chiseled', 'mcl_stairs:slab_quartz_chiseled')
minetest.register_alias('stairs:stair_coral_desert_stone_block', 'mcl_stairs:stair_coral_desert_stone_block')

minetest.register_alias('everness:cursed_brick_wall', 'everness:cursedbrickwall')
minetest.register_alias('walls:cobble', 'mcl_walls:cobble')
minetest.register_alias('xpanes:trapdoor_steel_bar', 'mcl_doors:iron_trapdoor')
minetest.register_alias('doors:trapdoor_open', 'mcl_doors:trapdoor_open')
minetest.register_alias('doors:trapdoor', 'mcl_doors:trapdoor')
minetest.register_alias('doors:door_wood_a', 'mcl_doors:wooden_door')
minetest.register_alias('doors:hidden', 'air')
minetest.register_alias('everness:cobweb', 'mcl_core:cobweb')

minetest.register_alias('fire:permanent_flame', 'air')
