lootchests.loot_table["lootchests_default:ocean_chest"] = {
    {"default:stick", 16},
    {"default:paper", 4},
    {"default:book", 3},
    {"default:skeleton_key", 1},
    {"default:flint", 4},
    {"default:obsidian_shard", 24},
    {"default:clay_brick", 32},
    {"default:mese_crystal_fragment", 4},
    {"default:gold_ingot", 8},
    {"default:bronze_ingot", 8},
    {"default:tin_ingot", 8},
    {"default:copper_ingot", 8},
    {"default:steel_ingot", 8},
    {"default:coal_lump", 16},
    {"default:pick_stone"},
    {"default:pick_bronze"},
    {"default:pick_steel"},
    {"default:shovel_stone"},
    {"default:shovel_bronze"},
    {"default:shovel_steel"},
    {"default:axe_stone"},
    {"default:axe_bronze"},
    {"default:axe_steel"},
    {"default:sword_stone"},
    {"default:sword_bronze"},
    {"default:sword_steel"},
    {"default:bookshelf", 4},
    {"default:sign_wall_wood", 2},
    {"default:ladder_wood", 32},
    {"default:ladder_steel", 16},
    {"default:glass", 24},
    {"default:obsidian_glass", 8},
    {"tnt:gunpowder", 16},
    {"vessels:glass_bottle", 8},
    {"vessels:drinking_glass", 8},
    {"screwdriver:screwdriver"},
    {"map:mapping_kit", 1},
    {"fire:flint_and_steel"},
    {"wool:white", 16},
    {"carts:rail", 24},
    {"carts:powerrail", 12},
    {"carts:brakerail", 12},
    {"carts:cart", 1},
    {"bucket:bucket_empty", 2},
    {"boats:boat", 1},
    {"binoculars:binoculars", 1},
    {
        "default:coral_green",
        "default:coral_pink",
        "default:coral_cyan",
        "default:coral_brown",
        "default:coral_orange",
        3,
    },
}

lootchests.loot_table["lootchests_default:basket"] = {
    {"default:stick", 16},
    {"default:tree", 4},
    {"default:jungletree", 4},
    {"default:pine_tree", 4},
    {"default:cactus", 4},
    {"default:large_cactus_seedling", 2},
    {"default:papyrus", 8},
    {"default:junglegrass", 4},
    {"default:grass_1", 4},
    {"default:blueberry_bush_sapling", 4},
    {
        "default:sapling",
        "default:junglesapling",
        "default:pine_sapling",
        "default:acacia_sapling",
        "default:aspen_sapling",
        1,
    },
    {
        "default:leaves",
        "default:acacia_leaves",
        "default:pine_needles",
        "default:aspen_leaves",
        "default:jungleleaves",
        10,
    },
    {"wool:white", 8},
    {"farming:wheat", 8},
    {"farming:flour", 4},
    {"farming:cotton", 4},
    {"farming:string", 4},
    {"flowers:mushroom_red", 8},
    {"ethereal:vine", 6},
    {"vessels:glass_bottle", 2},
}

lootchests.loot_table["lootchests_default:urn"] = {
    {"default:stick", 16},
    {"default:paper", 4},
    {"default:flint", 4},
    {"default:clay_lump", 16},
    {"default:tin_lump", 8},
    {"default:copper_lump", 8},
    {"default:iron_lump", 8},
    {"default:coal_lump", 16},
    {"default:pick_stone"},
    {"default:shovel_stone"},
    {"default:axe_stone"},
    {"default:sword_stone"},
    {"default:sign_wall_wood", 1},
    {"default:ladder_wood", 8},
    {"vessels:glass_bottle", 4},
    {"fire:flint_and_steel"},
    {"wool:white", 8},
    {"farming:flour", 4},
    {"default:tree", 2},
    {"default:jungletree", 2},
    {"default:pine_tree", 2},
    {"default:cobble", 60},
    {"caverealms:glow_gem", 6},
    {"default:gravel", 24},
    {"default:torch", 8},
    {"default:obsidian", 3}
}

lootchests.loot_table["lootchests_default:barrel"] = lootchests.loot_table["lootchests_default:urn"]

lootchests.loot_table["lootchests_default:stone_chest"] = {
    {"default:coalblock", 4},
    {"default:steelblock", 2},
    {"default:copperblock", 2},
    {"default:tinblock", 2},
    {"default:bronzeblock", 2},
    {"default:mese", 2},
    {"default:meselamp", 4},
    {"default:stick", 16},
    {"default:paper", 4},
    {"default:book", 3},
    {"default:skeleton_key", 1},
    {"default:flint", 4},
    {"default:obsidian", 24},
    {"default:clay_brick", 32},
    {"default:mese_crystal", 16},
    {"default:diamond", 16},
    {"default:gold_ingot", 16},
    {"default:bronze_ingot", 16},
    {"default:tin_ingot", 16},
    {"default:copper_ingot", 16},
    {"default:steel_ingot", 16},
    {"default:coal_lump", 32},
    {"default:pick_bronze"},
    {"default:pick_steel"},
    {"default:pick_mese"},
    {"default:shovel_bronze"},
    {"default:shovel_steel"},
    {"default:shovel_mese"},
    {"default:axe_bronze"},
    {"default:axe_steel"},
    {"default:axe_mese"},
    {"default:sword_bronze"},
    {"default:sword_steel"},
    {"default:sword_mese"},
    {"default:glass", 32},
    {"default:obsidian_glass", 16},
    {"tnt:gunpowder", 32},
    {"vessels:glass_bottle", 32},
    {"vessels:drinking_glass", 32},
    {"fire:flint_and_steel"},
    {"carts:rail", 64},
    {"carts:powerrail", 32},
    {"carts:brakerail", 32},
    {"carts:cart", 2},
    {"bucket:bucket_empty", 8},
    {"boats:boat", 2},
}